### ISSUE TITLE
Unable to run colab notebook

### ISSUE THREAD

**Issue by shekit** [tlatkowski/inpainting-gmcnn-keras#3]
Hi,

I'm trying to run the colab notebook but I keep getting the following error when running this line:

Actually it first gives an error saying `--experiment_name` is required, but after passing that arg in I get the error below

`!python inpainting-gmcnn-keras/runner.py --train_path images --mask_path mask -warm_up_generator --experiment_name tester`

`Traceback (most recent call last):
  File "inpainting-gmcnn-keras/runner.py", line 105, in <module>
    main()
  File "inpainting-gmcnn-keras/runner.py", line 52, in main
    config = main_config.MainConfig(MAIN_CONFIG_FILE)
  File "/content/inpainting-gmcnn-keras/config/main_config.py", line 22, in __init__
    self.model = ModelConfig(model_config['MODEL'])
  File "/content/inpainting-gmcnn-keras/config/main_config.py", line 41, in __init__
    self.add_mask_as_generator_input = parse_bool(model_section['ADD_MASK_AS_GENERATOR_INPUT'])
  File "/usr/lib/python3.6/configparser.py", line 1233, in __getitem__
    raise KeyError(key)
KeyError: 'ADD_MASK_AS_GENERATOR_INPUT'`

**Comment by tlatkowski** [comment]
Hi @shekit 

it looks like the colab notebook is outdated, i'm planning to fix it soon, thanks for pointing it out.

**Comment by GauravKrRoy** [comment]
> Hi @shekit
> 
> it looks like the colab notebook is outdated, i'm planning to fix it soon, thanks for pointing it out.
I am also facing the similar error. Can you please fix it.
Traceback (most recent call last):
  File "inpainting-gmcnn-keras/runner.py", line 105, in <module>
    main()
  File "inpainting-gmcnn-keras/runner.py", line 52, in main
    config = main_config.MainConfig(MAIN_CONFIG_FILE)
  File "/content/inpainting-gmcnn-keras/config/main_config.py", line 21, in __init__
    self.training = TrainingConfig(model_config['TRAINING'])
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'TRAINING'

**Comment by tlatkowski** [comment]
Hi @GauravKrRoy ,

I've just updated colab notebook, it should work fine now, please check it out.

BR
Tomasz
